 import type { NextPage } from "next";
import Head from "next/head";
import AppRouter from "../router/router";

const MainApp: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next SPA Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppRouter/>
    </div>
  );
};

export default MainApp;
